import { Routes } from '@angular/router';
import { authGuard } from './core/guards/auth.guard';
import { companyGuard } from './core/guards/company.guard';

export const routes: Routes = [
  { path: '', redirectTo: 'invoices', pathMatch: 'full' },
  { path: 'login', loadComponent: () => import('./auth/login/login.component').then(m => m.LoginComponent) },
  { path: 'profile', loadComponent: () => import('./auth/profile/profile.component').then(m => m.ProfileComponent), canActivate: [authGuard] },
  { path: 'invoices', loadComponent: () => import('./invoices/invoice-list/invoice-list.component').then(m => m.InvoiceListComponent), canActivate: [authGuard] },
  { path: 'invoices/new', loadComponent: () => import('./invoices/invoice-form/invoice-form.component').then(m => m.InvoiceFormComponent), canActivate: [authGuard] },
  { path: 'invoices/:id', loadComponent: () => import('./invoices/invoice-detail/invoice-detail.component').then(m => m.InvoiceDetailComponent), canActivate: [authGuard] },
  { path: 'invoices/:id/edit', loadComponent: () => import('./invoices/invoice-form/invoice-form.component').then(m => m.InvoiceFormComponent), canActivate: [authGuard] },
  { path: 'orders', loadComponent: () => import('./orders/order-list/order-list.component').then(m => m.OrderListComponent), canActivate: [authGuard] },
  { path: 'orders/new', loadComponent: () => import('./orders/order-form/order-form.component').then(m => m.OrderFormComponent), canActivate: [authGuard] },
  { path: 'orders/:id', loadComponent: () => import('./orders/order-detail/order-detail.component').then(m => m.OrderDetailComponent), canActivate: [authGuard] },
  { path: 'orders/:id/edit', loadComponent: () => import('./orders/order-form/order-form.component').then(m => m.OrderFormComponent), canActivate: [authGuard] },
  { path: 'delivery-notes', loadComponent: () => import('./delivery-notes/delivery-note-list/delivery-note-list.component').then(m => m.DeliveryNoteListComponent), canActivate: [authGuard] },
  { path: 'delivery-notes/new', loadComponent: () => import('./delivery-notes/delivery-note-form/delivery-note-form.component').then(m => m.DeliveryNoteFormComponent), canActivate: [authGuard] },
  { path: 'delivery-notes/:id', loadComponent: () => import('./delivery-notes/delivery-note-detail/delivery-note-detail.component').then(m => m.DeliveryNoteDetailComponent), canActivate: [authGuard] },
  { path: 'delivery-notes/:id/edit', loadComponent: () => import('./delivery-notes/delivery-note-form/delivery-note-form.component').then(m => m.DeliveryNoteFormComponent), canActivate: [authGuard] },
  { path: 'customers', loadComponent: () => import('./customers/customer-list/customer-list.component').then(m => m.CustomerListComponent), canActivate: [authGuard] },
  { path: 'customers/new', loadComponent: () => import('./customers/customer-form/customer-form.component').then(m => m.CustomerFormComponent), canActivate: [authGuard] },
  { path: 'customers/:id', loadComponent: () => import('./customers/customer-detail/customer-detail.component').then(m => m.CustomerDetailComponent), canActivate: [authGuard] },
  { path: 'customers/:id/edit', loadComponent: () => import('./customers/customer-form/customer-form.component').then(m => m.CustomerFormComponent), canActivate: [authGuard] },
  { path: 'main-account-codes', loadComponent: () => import('./main-account-codes/main-account-code-list/main-account-code-list.component').then(m => m.MainAccountCodeListComponent), canActivate: [authGuard] },
  { path: 'main-account-codes/new', loadComponent: () => import('./main-account-codes/main-account-code-form/main-account-code-form.component').then(m => m.MainAccountCodeFormComponent), canActivate: [authGuard] },
  { path: 'main-account-codes/:id/edit', loadComponent: () => import('./main-account-codes/main-account-code-form/main-account-code-form.component').then(m => m.MainAccountCodeFormComponent), canActivate: [authGuard] },
  { path: 'company', loadComponent: () => import('./company/company-settings/company-settings.component').then(m => m.CompanySettingsComponent), canActivate: [authGuard, companyGuard] },
  { path: 'firms', loadComponent: () => import('./firms/firm-list/firm-list.component').then(m => m.FirmListComponent), canActivate: [authGuard] },
  { path: 'firms/new', loadComponent: () => import('./firms/firm-form/firm-form.component').then(m => m.FirmFormComponent), canActivate: [authGuard] },
  { path: 'firms/:id', loadComponent: () => import('./firms/firm-detail/firm-detail.component').then(m => m.FirmDetailComponent), canActivate: [authGuard] },
  { path: 'employees', loadComponent: () => import('./employees/employee-list/employee-list.component').then(m => m.EmployeeListComponent), canActivate: [authGuard] },
  { path: 'employees/new', loadComponent: () => import('./employees/employee-form/employee-form.component').then(m => m.EmployeeFormComponent), canActivate: [authGuard] },
  { path: 'cash-registers', loadComponent: () => import('./cash-registers/cash-register-list/cash-register-list.component').then(m => m.CashRegisterListComponent), canActivate: [authGuard] },
  { path: 'cash-registers/new', loadComponent: () => import('./cash-registers/cash-register-form/cash-register-form.component').then(m => m.CashRegisterFormComponent), canActivate: [authGuard] },
  { path: 'cash-registers/:id', loadComponent: () => import('./cash-registers/cash-register-detail/cash-register-detail.component').then(m => m.CashRegisterDetailComponent), canActivate: [authGuard] },
  { path: 'cash-registers/:id/edit', loadComponent: () => import('./cash-registers/cash-register-form/cash-register-form.component').then(m => m.CashRegisterFormComponent), canActivate: [authGuard] },
  { path: 'bank-accounts', loadComponent: () => import('./bank-accounts/bank-account-list/bank-account-list.component').then(m => m.BankAccountListComponent), canActivate: [authGuard] },
  { path: 'bank-accounts/new', loadComponent: () => import('./bank-accounts/bank-account-form/bank-account-form.component').then(m => m.BankAccountFormComponent), canActivate: [authGuard] },
  { path: 'bank-accounts/:id', loadComponent: () => import('./bank-accounts/bank-account-detail/bank-account-detail.component').then(m => m.BankAccountDetailComponent), canActivate: [authGuard] },
  { path: 'bank-accounts/:id/edit', loadComponent: () => import('./bank-accounts/bank-account-form/bank-account-form.component').then(m => m.BankAccountFormComponent), canActivate: [authGuard] },
  { path: 'account-payments', loadComponent: () => import('./account-payments/account-payment-form/account-payment-form.component').then(m => m.AccountPaymentFormComponent), canActivate: [authGuard] },
  { path: 'products', loadComponent: () => import('./products/product-list/product-list.component').then(m => m.ProductListComponent), canActivate: [authGuard] },
  { path: 'products/new', loadComponent: () => import('./products/product-form/product-form.component').then(m => m.ProductFormComponent), canActivate: [authGuard] },
  { path: 'products/:id', loadComponent: () => import('./products/product-detail/product-detail.component').then(m => m.ProductDetailComponent), canActivate: [authGuard] },
  { path: 'products/:id/edit', loadComponent: () => import('./products/product-form/product-form.component').then(m => m.ProductFormComponent), canActivate: [authGuard] },
  { path: 'logs', loadComponent: () => import('./reports/log-list/log-list.component').then(m => m.LogListComponent), canActivate: [authGuard] },
  { path: 'reports', loadComponent: () => import('./reports/reports.component').then(m => m.ReportsComponent), canActivate: [authGuard] },
  { path: 'cheques', loadComponent: () => import('./cheques/cheque-list/cheque-list.component').then(m => m.ChequeListComponent), canActivate: [authGuard] },
  { path: 'cheques/new', loadComponent: () => import('./cheques/cheque-form/cheque-form.component').then(m => m.ChequeFormComponent), canActivate: [authGuard] },
  { path: 'cheques/:id', loadComponent: () => import('./cheques/cheque-detail/cheque-detail.component').then(m => m.ChequeDetailComponent), canActivate: [authGuard] },
  { path: 'cheques/:id/edit', loadComponent: () => import('./cheques/cheque-form/cheque-form.component').then(m => m.ChequeFormComponent), canActivate: [authGuard] },
  { path: '**', redirectTo: 'invoices' }
];
