/**
 * Material Icons ligature adları — `index.html`’deki `family=Material+Icons` (klasik web font) ile uyumlu olanlar.
 * Material Symbols’taki bazı adlar (ör. `dock_to_right`) bu fontta yoktur; liste ve alias buna göre tutulur.
 */
export const MATERIAL_ICONS_CURATED: readonly string[] = [
  'home',
  'dashboard',
  'menu',
  'menu_book',
  'widgets',
  'apps',
  'extension',
  'settings',
  'tune',
  'build',
  'manage_accounts',
  'admin_panel_settings',
  'person',
  'people',
  'groups',
  'badge',
  'business',
  'store',
  'inventory',
  'inventory_2',
  'category',
  'label',
  'shopping_cart',
  'point_of_sale',
  'receipt_long',
  'receipt',
  'description',
  'article',
  'folder',
  'folder_open',
  'inbox',
  'drafts',
  'mail',
  'email',
  'notifications',
  'campaign',
  'event',
  'calendar_today',
  'schedule',
  'task_alt',
  'checklist',
  'assignment',
  'account_balance',
  'account_balance_wallet',
  'payments',
  'attach_money',
  'savings',
  'trending_up',
  'trending_down',
  'analytics',
  'assessment',
  'bar_chart',
  'pie_chart',
  'table_chart',
  'show_chart',
  'summarize',
  'local_shipping',
  'place',
  'map',
  'public',
  'language',
  'search',
  'filter_list',
  'sort',
  'add',
  'remove',
  'close',
  'edit',
  'delete',
  'visibility',
  'visibility_off',
  'lock',
  'lock_open',
  'vpn_key',
  'security',
  'verified_user',
  'help',
  'info',
  'warning',
  'error',
  'check_circle',
  'cancel',
  'arrow_back',
  'arrow_forward',
  'chevron_right',
  'expand_more',
  'open_in_new',
  'link',
  'print',
  'download',
  'upload',
  'cloud_upload',
  'save',
  'refresh',
  'autorenew',
  'content_copy',
  'content_paste',
  'calculate',
  'percent',
  'factory',
  'precision_manufacturing',
  'handyman',
  'construction',
  'apartment',
  'corporate_fare',
  'work',
  'engineering',
  'science',
  'biotech',
  'school',
  'library_books',
  'history',
  'update',
  'sync_alt',
  'integration_instructions',
  'qr_code',
  'tag',
  'bookmark',
  'star',
  'favorite',
  'thumb_up',
  'support_agent',
  'contact_support',
  'phone',
  'chat',
  'forum',
  'lightbulb',
  'eco',
  'palette',
  'dark_mode',
  'light_mode',
  'image',
  'photo_camera',
  'attach_file',
  'note_add',
  'draw',
  'list',
  'view_list',
  'view_module',
  'grid_view',
  'splitscreen',
  'view_sidebar',
  'computer',
  'smartphone',
  'hub',
  'api',
  'code',
  'bug_report',
  'rule',
  'gavel',
  'balance',
  'account_tree',
  'schema',
  'dataset',
  'backup',
  'restore',
  'delete_forever'
];

export function filterMaterialIcons(
  query: string,
  icons: readonly string[] = MATERIAL_ICONS_CURATED
): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return [...icons];
  return icons.filter((name) => name.toLowerCase().includes(q));
}

/** Klasik Material+Icons webfontunda olmayan / yanlış adlar → geçerli ligature */
export const MATERIAL_ICON_LIGATURE_ALIASES: Readonly<Record<string, string>> = {
  dock_to_right: 'view_sidebar'
};

/**
 * Önizleme ve `<span class="material-icons">` için ligature; metin kutusu ham değeri tutabilir.
 */
export function resolveMaterialIconLigature(raw: string | null | undefined): string {
  if (raw == null || !String(raw).trim()) return 'help';
  const key = String(raw).trim();
  return MATERIAL_ICON_LIGATURE_ALIASES[key] ?? key;
}
