-- Tek Düzen Hesap Planı (THP) kodlarını MainAccountCodes tablosuna ekler.
-- Çalıştırmadan önce @FirmId değişkenine geçerli bir Firma Id atayın (örn. Firms tablosundan bir Id).
-- Kaynak: https://acikders.ankara.edu.tr/pluginfile.php/8707/mod_resource/content/1/THP.pdf

DECLARE @FirmId UNIQUEIDENTIFIER = '00000000-0000-0000-0000-000000000000'; -- Örn: SELECT TOP 1 Id FROM Firms
DECLARE @Now DATETIME2 = GETUTCDATE();

INSERT INTO MainAccountCodes (Id, FirmId, Code, Name, SortOrder, CreatedAt)
SELECT NEWID(), @FirmId, Code, Name, ROW_NUMBER() OVER (ORDER BY Code) - 1, @Now
FROM (VALUES
  -- 1. DÖNEN VARLIKLAR
  ('100', N'Kasa'),
  ('101', N'Alınan Çekler'),
  ('102', N'Bankalar'),
  ('103', N'Verilen Çekler ve Ödeme Emirleri (-)'),
  ('108', N'Diğer Hazır Değerler'),
  ('110', N'Hisse Senetleri'),
  ('111', N'Özel Kesim Tahvil, Senet ve Bonoları'),
  ('112', N'Kamu Kesimi Tahvil, Senet ve Bonoları'),
  ('118', N'Diğer Menkul Kıymetler'),
  ('119', N'Menkul Kıymetler Değer Düşüklüğü Karşılığı (-)'),
  ('120', N'Alıcılar'),
  ('121', N'Alacak Senetleri'),
  ('122', N'Alacak Senetleri Reeskontu (-)'),
  ('124', N'Kazanılmamış Finansal Kiralama Faiz Gelirleri (-)'),
  ('126', N'Verilen Depozito ve Teminatlar'),
  ('127', N'Diğer Ticari Alacak Senetleri ve Bonoları'),
  ('128', N'Şüpheli Ticari Alacaklar'),
  ('129', N'Şüpheli Ticari Alacaklar Karşılığı (-)'),
  ('131', N'Ortaklardan Alacaklar'),
  ('132', N'İştiraklerden Alacaklar'),
  ('133', N'Bağlı Ortaklıklardan Alacaklar'),
  ('135', N'Personelden Alacaklar'),
  ('136', N'Diğer Çeşitli Alacaklar'),
  ('137', N'Diğer Alacak Senetleri Reeskontu (-)'),
  ('138', N'Şüpheli Diğer Alacaklar'),
  ('139', N'Şüpheli Diğer Alacaklar Karşılığı (-)'),
  ('150', N'İlk Madde ve Malzeme'),
  ('151', N'Yarı Mamuller - Üretim'),
  ('152', N'Mamuller'),
  ('153', N'Ticari Mallar'),
  ('157', N'Diğer Stoklar'),
  ('158', N'Stok Değer Düşüklüğü Karşılığı (-)'),
  ('159', N'Verilen Sipariş Avansları'),
  ('170', N'Yıllara Yaygın İnşaat ve Onarım Maliyetleri'),
  ('178', N'Yıllara Yaygın İnşaat Enflasyon Düzeltmesi'),
  ('179', N'Taşeronlara Verilen Avanslar'),
  ('180', N'Gelecek Aylara Ait Giderler'),
  ('181', N'Gelir Tahakkukları'),
  ('190', N'Devreden KDV'),
  ('191', N'İndirilecek KDV'),
  ('192', N'Diğer KDV'),
  ('193', N'Peşin Ödenen Vergiler ve Fonlar'),
  ('195', N'İş Avansları'),
  ('196', N'Personel Avansları'),
  ('197', N'Sayım ve Tesellüm Noksanları'),
  ('198', N'Diğer Çeşitli Dönen Varlıklar'),
  ('199', N'Diğer Dönen Varlıklar Karşılığı (-)'),

  -- 2. DURAN VARLIKLAR
  ('220', N'Alıcılar'),
  ('221', N'Alacak Senetleri'),
  ('222', N'Alacak Senetleri Reeskontu (-)'),
  ('224', N'Kazanılmamış Finansal Kiralama Faiz Gelirleri (-)'),
  ('226', N'Verilen Depozito ve Teminatlar'),
  ('229', N'Şüpheli Alacaklar Karşılığı (-)'),
  ('231', N'Ortaklardan Alacaklar'),
  ('232', N'İştiraklerden Alacaklar'),
  ('233', N'Bağlı Ortaklıklardan Alacaklar'),
  ('235', N'Personelden Alacaklar'),
  ('236', N'Diğer Çeşitli Alacaklar'),
  ('237', N'Diğer Alacak Senetleri Reeskontu (-)'),
  ('239', N'Şüpheli Diğer Alacaklar Karşılığı (-)'),
  ('240', N'Bağlı Menkul Kıymetler'),
  ('241', N'Bağlı Menkul Kıymetler Değer Düşüklüğü Karşılığı (-)'),
  ('242', N'İştirakler'),
  ('243', N'İştiraklere Sermaye Taahhütleri (-)'),
  ('244', N'İştirakler Sermaye Payları Değer Düşüklüğü Karşılığı (-)'),
  ('245', N'Bağlı Ortaklıklar'),
  ('246', N'Bağlı Ortaklıklara Sermaye Taahhütleri (-)'),
  ('247', N'Bağlı Ortaklıklar Sermaye Payları Değer Düşüklüğü Karşılığı (-)'),
  ('248', N'Diğer Mali Duran Varlıklar'),
  ('249', N'Diğer Mali Duran Varlıklar Karşılığı (-)'),
  ('250', N'Arazi ve Arsalar'),
  ('251', N'Yeraltı ve Yerüstü Düzenleri'),
  ('252', N'Binalar'),
  ('253', N'Tesis, Makine ve Cihazlar'),
  ('254', N'Taşıtlar'),
  ('255', N'Demirbaşlar'),
  ('256', N'Diğer Maddi Duran Varlıklar'),
  ('257', N'Birikmiş Amortismanlar (-)'),
  ('258', N'Yapılmakta Olan Yatırımlar'),
  ('259', N'Verilen Avanslar'),
  ('260', N'Haklar'),
  ('261', N'Şerefiye'),
  ('262', N'Kuruluş ve Örgütlenme Giderleri'),
  ('263', N'Araştırma ve Geliştirme Giderleri'),
  ('264', N'Özel Maliyetler'),
  ('267', N'Diğer Maddi Olmayan Duran Varlıklar'),
  ('268', N'Birikmiş Amortismanlar (-)'),
  ('269', N'Verilen Avanslar'),
  ('271', N'Arama Giderleri'),
  ('272', N'Hazırlık ve Geliştirme Giderleri'),
  ('277', N'Diğer Özel Tükenmeye Tabi Varlıklar'),
  ('278', N'Birikmiş Tükenme Payları (-)'),
  ('279', N'Verilen Avanslar'),
  ('280', N'Gelecek Yıllara Ait Giderler'),
  ('281', N'Gelir Tahakkukları'),
  ('291', N'Gelecek Yıllarda İndirilecek KDV'),
  ('292', N'Diğer KDV'),
  ('293', N'Gelecek Yıllar İhtiyacı Stoklar'),
  ('294', N'Elden Çıkarılacak Stoklar ve Maddi Duran Varlıklar'),
  ('295', N'Peşin Ödenen Vergiler ve Fonlar'),
  ('297', N'Diğer Çeşitli Duran Varlıklar'),
  ('298', N'Stok Değer Düşüklüğü Karşılığı (-)'),
  ('299', N'Birikmiş Amortismanlar (-)'),

  -- 3. KISA VADELİ YABANCI KAYNAKLAR
  ('300', N'Banka Kredileri'),
  ('301', N'Finansal Kiralama İşlemlerinden Borçlar'),
  ('302', N'Ertelenmiş Finansal Kiralama Borçlanma Maliyetleri (-)'),
  ('303', N'Uzun Vadeli Kredilerin Anapara Taksitleri ve Faizleri'),
  ('304', N'Tahvil Anapara Borç, Taksit ve Faizleri'),
  ('305', N'Çıkarılmış Bonolar ve Senetler'),
  ('306', N'Çıkarılmış Diğer Menkul Kıymetler'),
  ('308', N'Menkul Kıymetler İhraç Farkları (-)'),
  ('309', N'Diğer Mali Borçlar'),
  ('320', N'Satıcılar'),
  ('321', N'Borç Senetleri'),
  ('322', N'Borç Senetleri Reeskontu (-)'),
  ('326', N'Alınan Depozito ve Teminatlar'),
  ('329', N'Diğer Ticari Borçlar'),
  ('331', N'Ortaklara Borçlar'),
  ('332', N'İştiraklere Borçlar'),
  ('333', N'Bağlı Ortaklıklara Borçlar'),
  ('335', N'Personele Borçlar'),
  ('336', N'Diğer Çeşitli Borçlar'),
  ('337', N'Diğer Borç Senetleri Reeskontu (-)'),
  ('340', N'Alınan Sipariş Avansları'),
  ('349', N'Alınan Diğer Avanslar'),
  ('350', N'Yıllara Yaygın İnşaat ve Onarım Hakedişleri'),
  ('358', N'Yıllara Yaygın İnşaat Enflasyon Düzeltmesi'),
  ('360', N'Ödenecek Vergi ve Fonlar'),
  ('361', N'Ödenecek Sosyal Güvenlik Kesintileri'),
  ('368', N'Vadesi Geçmiş, Ertelenmiş veya Taksitlendirilmiş Vergi ve Diğer Yükümlülükler'),
  ('369', N'Ödenecek Diğer Yükümlülükler'),
  ('370', N'Dönem Karı Vergi ve Diğer Yasal Yükümlülük Karşılıkları'),
  ('371', N'Dönem Karının Peşin Ödenen Vergi ve Diğer Yükümlülükleri (-)'),
  ('372', N'Kıdem Tazminatı Karşılığı'),
  ('373', N'Maliyet Giderleri Karşılığı'),
  ('379', N'Diğer Borç ve Gider Karşılıkları'),
  ('380', N'Gelecek Aylara Ait Gelirler'),
  ('381', N'Gider Tahakkukları'),
  ('391', N'Hesaplanan KDV'),
  ('392', N'Diğer KDV'),
  ('393', N'Merkez ve Şubeler Cari Hesabı'),
  ('397', N'Sayım ve Tesellüm Fazlaları'),
  ('399', N'Diğer Çeşitli Yabancı Kaynaklar'),

  -- 4. UZUN VADELİ YABANCI KAYNAKLAR
  ('400', N'Banka Kredileri'),
  ('401', N'Finansal Kiralama İşlemlerinden Borçlar'),
  ('402', N'Ertelenmiş Finansal Kiralama Borçlanma Maliyetleri (-)'),
  ('405', N'Çıkarılmış Tahviller'),
  ('407', N'Çıkarılmış Diğer Menkul Kıymetler'),
  ('408', N'Menkul Kıymetler İhraç Farkı (-)'),
  ('409', N'Diğer Mali Borçlar'),
  ('420', N'Satıcılar'),
  ('421', N'Borç Senetleri'),
  ('422', N'Borç Senetleri Reeskontu (-)'),
  ('426', N'Alınan Depozito ve Teminatlar'),
  ('429', N'Diğer Ticari Borçlar'),
  ('431', N'Ortaklara Borçlar'),
  ('432', N'İştiraklere Borçlar'),
  ('433', N'Bağlı Ortaklıklara Borçlar'),
  ('436', N'Diğer Çeşitli Borçlar'),
  ('437', N'Diğer Borçlar Senetleri Reeskontu (-)'),
  ('438', N'Kamuya Olan Ertelenmiş veya Taksitlendirilmiş Borçlar'),
  ('440', N'Alınan Sipariş Avansları'),
  ('449', N'Alınan Diğer Avanslar'),
  ('472', N'Kıdem Tazminatı Karşılığı'),
  ('479', N'Diğer Borç ve Gider Karşılıkları'),
  ('480', N'Gelecek Yıllara Ait Gelirler'),
  ('481', N'Gider Tahakkukları'),
  ('492', N'Gelecek Yıllara Ertelenen veya Terkin Edilecek KDV'),
  ('493', N'Tesise Katılma Payları'),
  ('499', N'Diğer Çeşitli Uzun Vadeli Yabancı Kaynaklar'),

  -- 5. ÖZ KAYNAKLAR
  ('500', N'Sermaye'),
  ('501', N'Ödenmemiş Sermaye (-)'),
  ('502', N'Sermaye Düzeltmesi Olumlu Farkları'),
  ('503', N'Sermaye Düzeltmesi Olumsuz Farklar (-)'),
  ('520', N'Hisse Senedi İhraç Primleri'),
  ('521', N'Hisse Senedi İptal Karları'),
  ('522', N'MDV Yeniden Değerleme Artışları'),
  ('523', N'İştirakler Yeniden Değerleme Artışları'),
  ('524', N'Maliyet Artışları Fonu'),
  ('529', N'Diğer Sermaye Yedekleri'),
  ('540', N'Yasal Yedekler'),
  ('541', N'Statü Yedekleri'),
  ('542', N'Olağanüstü Yedekler'),
  ('548', N'Diğer Kar Yedekleri'),
  ('549', N'Özel Fonlar'),
  ('570', N'Geçmiş Yıllar Karları'),
  ('580', N'Geçmiş Yıllar Zararları (-)'),
  ('590', N'Dönem Net Karı'),
  ('591', N'Dönem Net Zararı (-)'),

  -- 6. GELİR TABLOSU HESAPLARI
  ('600', N'Yurtiçi Satışlar'),
  ('601', N'Yurtdışı Satışlar'),
  ('602', N'Diğer Gelirler'),
  ('610', N'Satıştan İadeler (-)'),
  ('611', N'Satış İskontoları (-)'),
  ('612', N'Diğer İndirimler (-)'),
  ('620', N'Satılan Mamuller Maliyeti (-)'),
  ('621', N'Satılan Ticari Mallar Maliyeti (-)'),
  ('622', N'Satılan Hizmet Maliyeti (-)'),
  ('623', N'Diğer Satışların Maliyeti (-)'),
  ('630', N'Araştırma ve Geliştirme Giderleri (-)'),
  ('631', N'Pazarlama, Satış ve Dağıtım Giderleri (-)'),
  ('632', N'Genel Yönetim Giderleri (-)'),
  ('640', N'İştiraklerden Temettü Gelirleri'),
  ('641', N'Bağlı Ortaklıklardan Temettü Gelirleri'),
  ('642', N'Faiz Gelirleri'),
  ('643', N'Komisyon Gelirleri'),
  ('644', N'Konusu Kalmayan Karşılıklar'),
  ('645', N'Menkul Kıymet Satış Karları'),
  ('646', N'Kambiyo Karları'),
  ('647', N'Reeskont Faiz Gelirleri'),
  ('648', N'Enflasyon Düzeltmesi Karları'),
  ('649', N'Diğer Olağan Gelir ve Karlar'),
  ('653', N'Komisyon Giderleri (-)'),
  ('654', N'Karşılık Giderleri (-)'),
  ('655', N'Menkul Kıymet Satış Zararları (-)'),
  ('656', N'Kambiyo Zararları (-)'),
  ('657', N'Reeskont Faiz Giderleri (-)'),
  ('658', N'Enflasyon Düzeltmesi Zararları (-)'),
  ('659', N'Diğer Olağan Gider ve Zararlar (-)'),
  ('660', N'Kısa Vadeli Borçlanma Giderleri (-)'),
  ('661', N'Uzun Vadeli Borçlanma Giderleri (-)'),
  ('671', N'Önceki Dönem Gelir ve Karları'),
  ('679', N'Diğer Olağandışı Gelir ve Karlar'),
  ('680', N'Çalışmayan Kısım Gider ve Zararları (-)'),
  ('681', N'Önceki Dönem Gider ve Zararları (-)'),
  ('689', N'Diğer Olağandışı Gider ve Zararlar (-)'),
  ('690', N'Dönem Karı veya Zararı'),
  ('691', N'Dönem Karı Vergi ve Diğer Yasal Yükümlülük Karşılıkları (-)'),
  ('692', N'Dönem Net Karı veya Zararı'),

  -- 7. MALİYET HESAPLARI (7/A)
  ('700', N'Maliyet Muhasebesi Bağlantı Hesapları'),
  ('701', N'Maliyet Muhasebesi Yansıtma Hesabı'),
  ('710', N'Direkt İlk Madde ve Malzeme Giderleri'),
  ('711', N'Direkt İlk Madde ve Malzeme Yansıtma Hesabı'),
  ('712', N'Direkt İlk Madde ve Malzeme Fiyat Farkı'),
  ('713', N'Direkt İlk Madde ve Malzeme Miktar Farkı'),
  ('720', N'Direkt İşçilik Giderleri'),
  ('721', N'Direkt İşçilik Giderleri Yansıtma Hesabı'),
  ('722', N'Direkt İşçilik Ücret Farkları'),
  ('723', N'Direkt İşçilik Süre (Zaman) Farkları'),
  ('730', N'Genel Üretim Giderleri'),
  ('731', N'Genel Üretim Giderleri Yansıtma Hesabı'),
  ('732', N'Genel Üretim Giderleri Bütçe Farkları'),
  ('733', N'Genel Üretim Giderleri Verimlilik Farkları'),
  ('734', N'Genel Üretim Giderleri Kapasite Farkları'),
  ('740', N'Hizmet Üretim Maliyeti'),
  ('741', N'Hizmet Üretim Maliyeti Yansıtma Hesabı'),
  ('742', N'Hizmet Üretim Maliyeti Fark Hesapları'),
  ('750', N'Araştırma ve Geliştirme Giderleri'),
  ('751', N'Araştırma ve Geliştirme Giderleri Yansıtma Hesabı'),
  ('752', N'Araştırma ve Geliştirme Gider Farkları'),
  ('760', N'Pazarlama, Satış ve Dağıtım Giderleri'),
  ('761', N'Pazarlama, Satış ve Dağıtım Giderleri Yansıtma Hesabı'),
  ('762', N'Pazarlama, Satış ve Dağıtım Giderleri Fark Hesabı'),
  ('770', N'Genel Yönetim Giderleri'),
  ('771', N'Genel Yönetim Giderleri Yansıtma Hesabı'),
  ('772', N'Genel Yönetim Gider Farkları Hesabı'),
  ('780', N'Finansman Giderleri'),
  ('781', N'Finansman Giderleri Yansıtma Hesabı'),
  ('782', N'Finansman Giderleri Fark Hesabı'),

  -- 7/B SEÇENEĞİ
  ('790', N'İlk Madde ve Malzeme Giderleri'),
  ('791', N'İşçi Ücret ve Giderleri'),
  ('792', N'Memur Ücret ve Giderleri'),
  ('793', N'Dışarıdan Sağlanan Fayda ve Hizmetler'),
  ('794', N'Çeşitli Giderler'),
  ('795', N'Vergi, Resim ve Harçlar'),
  ('796', N'Amortismanlar ve Tükenme Payları'),
  ('797', N'Finansman Giderleri'),
  ('798', N'Gider Çeşitleri Yansıtma Hesabı'),
  ('799', N'Üretim Maliyet Hesabı')
) AS T(Code, Name);
